### ISSUE TITLE
Is the parse library floss?

### ISSUE THREAD

**Issue by krt16s** [mattieapps/roommates#5]
I try to update your app on f-droid.org, a "store" for free/libre/open-source software on Android. Is the parse library floss? If so, could you point me to source code? If not: Can it be easily removed?

**Comment by mattieapps** [comment]
@krt16s The Parse.com library is used to send push notifications to users when there is a new app update in the Play Store. The library is proprietary to Parse but it is not crucial for app functionality as the rest of the app functions without it. I have setup a new folder called "roommates-android-noparse" that has no trace of the library. Let me know if you have any other questions.

**Comment by krt16s** [comment]
Thanks for the quick reply, works fine now. The update should be ready within 48hrs (because I just missed the merge window for tonights builds). 

Depending on how much effort it is to maintain two seperate version, you could also look into gradle's build flavors or just provide a patchset. But for now everything is fine. Thanks again :)
