### ISSUE TITLE
github code differs from google play

### ISSUE THREAD

**Issue by fischerling** [mattieapps/roommates#6]
I noticed that on google play there is a 2.0 release, but the code is not released on github.

Have you changed the repository location or the licence or are you going to publish the code on github in near future ?

**Comment by mattieapps** [comment]
Yes, source for 2.0 will be pushed tomorrow

**Comment by fischerling** [comment]
I don't want to bother you but when are you releasing the code ?

Actually why aren't you pushing all your developent progress ?

**Comment by mattieapps** [comment]
Source will be pushed when the next update is ready, still trying to figure out some things before pushing.

**Comment by mattieapps** [comment]
Source code is being pushed regularly now
